apiVersion: v1
kind: Namespace
metadata:
  name: galaxy-dev
  labels:
    name: galaxy-dev
---
apiVersion: v1
kind: ResourceQuota
metadata:
  namespace: galaxy-dev
  name: galaxy-dev
  labels:
    name: galaxy-dev
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  namespace: galaxy-dev
  name: galaxy-dev
  labels:
    name: galaxy-dev
spec:
  limits:
  - default:
      memory: 256Mi
      #cpu: 500m
      cpu: 200m
    defaultRequest:
      memory: 256Mi
      #cpu: 500m
      cpu: 200m
    type: Container
    max:
      #memory: 512Mi
      memory: 1000Mi
      cpu: 2
    min:
      memory: 100Mi
      cpu: 100m
    type: Container