
spring:
  application:
    name: ms-admin-gateway-server
  cloud:
    gateway:
      routes:
      - id:  ms-customer-management
        uri:  lb://ms-customer-management
        predicates:
          - Path=/api/customer/**
        filters:
          - StripPrefix=2
      - id:  ms-admin-oauth
        uri:  lb://ms-admin-oauth
        predicates:
          - Path=/api/security/**
        filters:
          - StripPrefix=2
      - id:  ms-admin-user
        uri:  lb://ms-admin-user
        predicates:
          - Path=/api/usuarios/**
        filters:
          - StripPrefix=2
server:
  port: 8891
eureka:
   instance:
      hostname: localhost
   client:
        register-with-eureka: true
        fetch-registry: true
        serviceUrl:
           defaultZone: http://localhost:8761/eureka
   wait-time-in-ms-when-sync-empty: 0
   
config:
  security:
    oauth:
      jwt.key: galaxy2022123456789natanael 