version: "3.5"

services:
  server:
    image: container-registry.oracle.com/database/enterprise:12.2.0.1-slim
    container_name: followup-database-oracle
    environment:
      - ORACLE_SID=ORCLCDB
      - ORACLE_EDITION=standard # enterprise
      - ORACLE_PWD=oracle
    volumes:
      - "/home/natanael/developer/java-dev/docker/docker-volumes/data/oracledb-12.0.1-slim:/ORCL" 
      # Validar si es por el uso de la version SLIM, en la documentacion indica que la data esta en /opt/oracle/oradata
      #- "/home/natanael/developer/java-dev/docker/docker-volumes/data/oracledb-12.0.1-slim:/opt/oracle/oradata"
    ports:
      - "1522:1521"
      - "5501:5500"
    networks:
    - net-followup-ms
  mysql:
    image: mysql:8.0.29
    container_name: followup-database-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: FOLLOWUP_CUSTOMER
      MYSQL_USER: FOLLOWUP_MS_2022_CUSTOMER
      MYSQL_PASSWORD: mysql
    ports:
    - 3307:3306
    - 33061:33060
    volumes:
      - "/home/natanael/developer/java-dev/docker/docker-volumes/data/mysqldb-8:/var/lib/mysql"
    networks:
    - net-followup-ms
networks:
  net-followup-ms:
    name: net-followup-ms-db

