
server:
  port: 8890
spring:
  application:
    name: ms-admin-server-admin
#  boot:
#    admin:
#      discovery:
#        ignored-services: ms-admin-server-admin

# Registry Client
eureka:
   client:
      registryFetchIntervalSeconds: 5
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka