server:
  port: 8083
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/followup_treatment
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
logging:
  level:
    org.hibernate.sql: debug
# Registry Client
eureka:
   client:
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka
# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
#add custom information to actuator endpoint info
info:
  application:
    name: Treatment Management
    description: MS Treatment