CREATE TABLE ORDEN(
    ID_ORDEN NUMERIC(6) NOT NULL PRIMARY KEY,
    ID_CLIENTE NUMERIC(6) NOT NULL,
    GLOSA VARCHAR2(240) NULL,
    FECHA_REGISTRO DATE DEFAULT SYSDATE,
    
    TOTAL NUMERIC(9,2) NOT NULL,
    ESTADO CHAR(1) DEFAULT '1' NOT NULL
);

CREATE SEQUENCE SEQ_ORDEN;

INSERT INTO ORDEN(ID_ORDEN,ID_CLIENTE,GLOSA,TOTAL) VALUES(SEQ_ORDEN.NEXTVAL, 1,'Orden demo',6090);
COMMIT;
SELECT * FROM ORDEN;

CREATE TABLE ORDEN_ITEM(
    ID_ORDEN_ITEM NUMERIC(6) NOT NULL PRIMARY KEY,
    ID_ORDEN NUMERIC(6) REFERENCES ORDEN(ID_ORDEN),
    ID_PRODUCTO NUMERIC(6) NOT NULL,
    CANTIDAD NUMERIC(6) NOT NULL,
    PRECIO NUMERIC(6,2) NOT NULL,
    SUB_TOTAL NUMERIC(9,2) NOT NULL,
    
    ESTADO CHAR(1) DEFAULT '1' NOT NULL
);

CREATE SEQUENCE SEQ_ORDEN_ITEM;

INSERT INTO ORDEN_ITEM(ID_ORDEN_ITEM,ID_ORDEN,ID_PRODUCTO,CANTIDAD,PRECIO,SUB_TOTAL) VALUES(SEQ_ORDEN_ITEM.NEXTVAL, 1,1,3,30,90);
INSERT INTO ORDEN_ITEM(ID_ORDEN_ITEM,ID_ORDEN,ID_PRODUCTO,CANTIDAD,PRECIO,SUB_TOTAL) VALUES(SEQ_ORDEN_ITEM.NEXTVAL, 1,2,1,6000,6000);
COMMIT;
SELECT * FROM ORDEN_ITEM;
