


spring:
  application:
    name: ms-treatment-command
  profiles:
    active: native
  config:    
    import: configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: true
      retry:
         max-attempts: 20
         max-interval: 15000
         initial-interval: 10000
#  config:
#    import: "optional:configserver:"