apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: galaxy-dev
  name: app-deployment-admin-oauth
  labels:
    app: service-admin-oauth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-admin-oauth
  template:
    metadata:
      labels:
        app: service-admin-oauth
    spec:
      containers:
      - name: service-admin-oauth
        #image: acraforo255fv.azurecr.io/apptransaction:#{Build.BuildId}#
        image: service-admin-oauth
        #image: natanaelza/service-admin-oauth:v1
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: aforo.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: galaxy-dev
  name: app-deployment-admin-user
  labels:
    app: service-admin-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-admin-user
  template:
    metadata:
      labels:
        app: service-admin-user
    spec:
      containers:
      - name: service-admin-user
        #image: acraforo255fv.azurecr.io/apptransaction:#{Build.BuildId}#
        image: service-admin-user
        #image: natanaelza/service-admin-user:v1
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: aforo.com
---
kind: Service
apiVersion: v1
metadata:
  namespace: galaxy-dev
  name: app-service-admin-oauth
spec:
  type: LoadBalancer
  selector:
    app: service-admin-oauth
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
kind: Service
apiVersion: v1
metadata:
  namespace: galaxy-dev
  name: app-service-admin-user
spec:
  type: LoadBalancer
  selector:
    app: service-admin-user
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80